language: python
python: 2.7
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=pep8
    - python: 3.6
      env: TOX_ENV=mypy
install:
 - pip install tox
script:
 - tox
