[package]
name = "cenv"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[main]
name = "cenv"
crate-type = ["cdylib", "lib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
eyre = "0.6.12"
pyo3 = "0.24.0"


