[project]
name = "cenv"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = { find = { where = ["python"]}}

[build-system]
requires = ["maturin>=1.8.3,<2.0"]
build-backend = "maturin"

# [tool.maturin]
# bindings = "cffi"
# compatibility = "linux"

[project.scripts]
cenv = "cenv.cli:main"

[dependency-groups]
dev = [
    "coverage>=7.7.1",
    "maturin>=1.8.3",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
]

[tool.maturin]
python-source = "python"
module-name = "cenv._cenv"
features = ["pyo3/extension-module"]

