[tox]
envlist = py37
skipsdist = true

[testenv:py37]
deps =
    cget
    coverage
    mypy==0.550
    pytest
    six
    typing
commands =
    python {toxinidir}/tox/save_path.py {toxinidir}/tox/py36_path.txt
    python {toxinidir}/tox/run_py36.py
